"""
config.py
=========
All the "knobs" for the pipeline live here, in one place, so you never have
to hunt through the other files to change a model name or a folder path.
"""

import os

# ---------------------------------------------------------------------------
# Folders
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
KNOWLEDGE_DOCS_DIR = os.path.join(BASE_DIR, "data", "knowledge_docs")
SAMPLE_REPORTS_DIR = os.path.join(BASE_DIR, "data", "sample_reports")
INDEX_CACHE_PATH = os.path.join(BASE_DIR, "data", "vector_index_cache.pkl")

# ---------------------------------------------------------------------------
# Retriever
# ---------------------------------------------------------------------------
# How many knowledge snippets to hand to the vision-language model per test.
TOP_K_RESULTS = 3

# ---------------------------------------------------------------------------
# Vision-language model
# ---------------------------------------------------------------------------
# Any OpenAI-compatible chat endpoint works here. Swap BASE_URL + MODEL_NAME
# to point at a hosted Qwen2.5-VL server instead of OpenAI, if you prefer.
VLM_PROVIDER = os.environ.get("VLM_PROVIDER", "openai")  # "openai" or "qwen"
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL_NAME = os.environ.get("OPENAI_MODEL_NAME", "gpt-4.1")

# If you're running a local/hosted Qwen2.5-VL server that speaks the
# OpenAI-compatible API, point these at it instead.
QWEN_BASE_URL = os.environ.get("QWEN_BASE_URL", "http://localhost:8000/v1")
QWEN_API_KEY = os.environ.get("QWEN_API_KEY", "not-needed")
QWEN_MODEL_NAME = os.environ.get("QWEN_MODEL_NAME", "qwen2.5-vl-7b-instruct")

# ---------------------------------------------------------------------------
# Safety / behavior
# ---------------------------------------------------------------------------
# The final report always carries this disclaimer — the pipeline supports a
# clinician's judgement, it does not replace one.
MEDICAL_DISCLAIMER = (
    "This report is generated by an AI pipeline for informational purposes "
    "only. It is not a medical diagnosis. Please discuss these results with "
    "a licensed healthcare provider."
)
